[package]
name = "mqttrust"
version = "0.0.5"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "MQTT Client "
readme = "README.md"
keywords = ["mqtt", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/mqttrust"
edition = "2018"
documentation = "https://docs.rs/mqttrust"

[lib]
name = "mqttrust"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = "^0.2"
nb = "^0.1"
heapless = { version = "^0.5.5", features = ["serde"] }
no-std-net = "*"
embedded-nal = { git = "https://github.com/MathiasKoch/embedded-nal", branch = "factbird_mini" }
mqttrs = { git = "https://github.com/MathiasKoch/mqttrs", branch = "wip/alloc-free-encode", default-features = false }

defmt = { git = "https://github.com/knurling-rs/defmt", branch = "main" }

[dev-dependencies]
void = { version = "1.0.2", default-features = false }
dns-lookup = "1.0.3"


[features]
default = []

alloc = []

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
