[package]
name = "mqttrust"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "MQTT Client "
readme = "README.md"
keywords = ["mqtt", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/mqttrust"
edition = "2018"
documentation = "https://docs.rs/mqttrust"

[lib]
name = "mqttrust"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = "0.2.3"
nb = "0.1.2"
ufmt = "0.1.0"
heapless = { version = "0.5.3", features = ["serde"] }
log = { version = "0.4", default-features = false, optional = true }
bytes = { version = "0.5.4", default-features = false }
embedded-nal = { git = "https://github.com/thejpster/embedded-nal" }
no-std-net = "0.3.0"
mqttrs = { path = "../mqttrs", default-features = false }
# mqttrs = { version = "0.3.0", default-features = false }

[dev-dependencies]
void = { version = "1.0.2", default-features = false }
env_logger = "0.7.1"

[features]

logging = ["log"]
