[package]
name = "mqttrust"
version = "0.0.1"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "MQTT Client "
readme = "README.md"
keywords = ["mqtt", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/mqttrust"
edition = "2018"
documentation = "https://docs.rs/mqttrust"

[lib]
name = "mqttrust"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = "0.2.3"
nb = "0.1.2"
ufmt = "0.1.0"
heapless = { version = "0.5.3", features = ["serde"] }
log = { version = "0.4", default-features = false }
mqttrs = { git = "https://github.com/00imvj00/mqttrs", default-features = false }
bytes = { version = "0.5.4", default-features = false }
embedded-nal = { git = "https://github.com/thejpster/embedded-nal" }

[dev-dependencies]
void = "1.0.2"
env_logger = "0.7.1"
